### ISSUE TITLE
Value of type null is not callable

### ISSUE THREAD

**Issue by KaptenZee** [xBeastMode/WorldInventory#1]
private function save(string $world, Player $player, ?Closure $onFinished = null): void{
                switch($this->plugin->getWorldInventoryType($world)){
                        case "linked":
                                $this->plugin->savePlayerWorldInventory("linked", $player, $onFinished);
                                break;
                        case "saved":
                                $this->plugin->savePlayerWorldInventory($world, $player, $onFinished);
                                break;
                        default:
                                $onFinished();
                                break;
                }
        }

        /**
         * Fetches player's world inventory contents based on world inventory type
         *
         * @param string $world
         * @param Player $player
         */

**Comment by xBeastMode** [comment]
Hello! Thank you for your report. This issue should be fixed on latest build: https://poggit.pmmp.io/r/190385/WorldInventory_dev-22.phar

I will submit this build asap.
